trigger:
  branches:
    include:
      - main

pool:
  name: Default

variables:
  AZURE_SUBSCRIPTION: 'My Azure Subscription'
  RESOURCE_GROUP: 'shared-rg'

stages:
  - stage: DeployHelm
    jobs:
      - job: Deploy
        steps:
          - checkout: self
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(AZURE_SUBSCRIPTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az bicep install
                az deployment group create \
                  --resource-group $(RESOURCE_GROUP) \
                  --template-file infra/main.bicep
